Added TS types to eris-pagination
riyacchi/eris-pagination pull request #7
Opened 2019-09-07 11:18 UTC by CircuitCodes

This will obviously bring easier TypeScript support to the library.

2019-09-14 15:31 UTC, riyacchi commented
Hey, thanks for the PR! I'll have it reviewed ASAP and have it merged if nothing is wrong with the typings.

2019-09-14 17:38 UTC, eritbh requested changes

2019-09-14 17:38 UTC, Geo1088 commented on package.json
>    }
Not strictly necessary, but Typescript docs say it's advisable to add the `"types"` key even when the typing file is `index.d.ts.`.

2019-09-14 17:38 UTC, Geo1088 commented on index.d.ts
> +    }
This class definition isn't necessary since it isn't accessible to API consumers. It should be removed.

2019-09-14 17:38 UTC, Geo1088 commented on index.d.ts
> +    export function createPaginationEmbed(message: Message, pages: EmbedOptions[], options?: PaginationEmbedOptions): Promise<void>;
`export` is implied inside `declare` blocks. Definitions should be consistent about using it - either include or omit the `export` keyword on everything inside `declare`. I suggest using it on everything for clarity.

2020-02-05 17:15 UTC, bsian03 commented
The user looks like they deleted their fork of the repository, I just wrote up my own typings file, do you want me to submit a PR?

2020-02-05 17:16 UTC, riyacchi commented
> The user looks like they deleted their fork of the repository, I just wrote up my own typings file, do you want me to submit a PR?

That'd be really appreciated!

2020-02-05 17:17 UTC, riyacchi commented
Closing due to inactivity.

2020-02-05 17:17 UTC, closed without merging