Cycling
riyacchi/eris-pagination pull request #9
Opened 2019-09-18 18:38 UTC by nesmon

Add cycling option for go to the first page when reach last and click on next 
or go to last when click on back at first page

2019-09-18 18:55 UTC, riyacchi commented on lib/PaginationEmbed.js
> +        this.cycling = options.cycling    || false
Indentation is messed up and should be indented with the other properties.

2019-09-18 19:00 UTC, knht requested changes

2019-09-18 19:00 UTC, knht commented on lib/PaginationEmbed.js
> +
Unnecessary line should be removed
```suggestion
```

2019-09-18 19:00 UTC, knht commented on lib/PaginationEmbed.js
> +        this.cycling = options.cycling    || false
Indentation is messed up and should be indented with the other properties.

2019-09-18 19:00 UTC, knht commented on lib/PaginationEmbed.js
> +     * @property {Boolean} options.cycling If back to rist page when you click on next in last page or click last page when you click on back in first page. Defaults to: false
The english isn't in line with the rest of the documentation and contains typos.

```suggestion
     * @property {Boolean} options.cycling Cycle through all embeds jumping from the first page to the last page on going back and from the last page to the first page going forth. Defaults to: false
```

2019-09-18 19:00 UTC, knht commented on README.md
> +    - **Boolean** `options.cycling` - If back to rist page when you click on next in last page or click last page when you click on back in first page.
Same issue as the JSDoc
```suggestion
    - **Boolean** `options.cycling` - Cycle through all embeds jumping from the first page to the last page on going back and from the last page to the first page going forth.
```

2019-09-19 06:35 UTC, nesmon commented
I update the repo with suggest send me

2019-09-19 07:47 UTC, knht requested changes
The changes made are fine, but you're missing the previously pointed out indentation in line 40

2019-09-19 08:29 UTC, knht approved these changes

2019-09-19 08:31 UTC, merged